version: 2.1

            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
                cd frontend
                npm install
                npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
                npm install
                npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      -   checkout
      - restore_cache:
          keys: [test-frontend]
      - run:
          name: Install dependencies
          working_directory: ./frontend
          command:  |
                npm install
      - run:
          name: Frontend test
          working_directory: ./frontend
          command:  |
                npm run test
      - save_cache:
          paths: [frontend/node_modules]
          key: test-frontend

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      -   checkout
      - restore_cache:
          keys: [test-backend]
      - run:
          name: Install dependencies
          working_directory: ./backend
          command:  |
                npm install
      - run:
          name: Backend test
          working_directory: ./backend
          command:  |
                npm run test
      - save_cache:
          paths: [backend/node_modules]
          key: test-backend

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
